// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: config_update.proto
// Protobuf C++ Version: 6.30.0

#include "config_update.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace cs {

inline constexpr ConfigUpdate_Response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        err_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConfigUpdate_Response::ConfigUpdate_Response(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ConfigUpdate_Response_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ConfigUpdate_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConfigUpdate_ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConfigUpdate_ResponseDefaultTypeInternal() {}
  union {
    ConfigUpdate_Response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConfigUpdate_ResponseDefaultTypeInternal _ConfigUpdate_Response_default_instance_;

inline constexpr ConfigUpdate_Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : update_file_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ConfigUpdate_Request::ConfigUpdate_Request(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ConfigUpdate_Request_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ConfigUpdate_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConfigUpdate_RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConfigUpdate_RequestDefaultTypeInternal() {}
  union {
    ConfigUpdate_Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConfigUpdate_RequestDefaultTypeInternal _ConfigUpdate_Request_default_instance_;

inline constexpr ConfigUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        request_{nullptr},
        response_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ConfigUpdate::ConfigUpdate(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ConfigUpdate_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ConfigUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConfigUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConfigUpdateDefaultTypeInternal() {}
  union {
    ConfigUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConfigUpdateDefaultTypeInternal _ConfigUpdate_default_instance_;
}  // namespace cs
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_config_5fupdate_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_config_5fupdate_2eproto = nullptr;
const ::uint32_t
    TableStruct_config_5fupdate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::cs::ConfigUpdate_Request, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cs::ConfigUpdate_Request, _impl_.update_file_),
        PROTOBUF_FIELD_OFFSET(::cs::ConfigUpdate_Response, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::cs::ConfigUpdate_Response, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cs::ConfigUpdate_Response, _impl_.err_),
        0,
        PROTOBUF_FIELD_OFFSET(::cs::ConfigUpdate, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::cs::ConfigUpdate, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::cs::ConfigUpdate, _impl_.request_),
        PROTOBUF_FIELD_OFFSET(::cs::ConfigUpdate, _impl_.response_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::cs::ConfigUpdate_Request)},
        {9, 18, -1, sizeof(::cs::ConfigUpdate_Response)},
        {19, 29, -1, sizeof(::cs::ConfigUpdate)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::cs::_ConfigUpdate_Request_default_instance_._instance,
    &::cs::_ConfigUpdate_Response_default_instance_._instance,
    &::cs::_ConfigUpdate_default_instance_._instance,
};
const char descriptor_table_protodef_config_5fupdate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023config_update.proto\022\002cs\032\nbase.proto\"\237\001"
    "\n\014ConfigUpdate\022)\n\007request\030\001 \001(\0132\030.cs.Con"
    "figUpdate.Request\022+\n\010response\030\002 \001(\0132\031.cs"
    ".ConfigUpdate.Response\032\036\n\007Request\022\023\n\013upd"
    "ate_file\030\001 \003(\t\032\027\n\010Response\022\013\n\003err\030\001 \001(\005b"
    "\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_config_5fupdate_2eproto_deps[1] = {
        &::descriptor_table_base_2eproto,
};
static ::absl::once_flag descriptor_table_config_5fupdate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_config_5fupdate_2eproto = {
    false,
    false,
    207,
    descriptor_table_protodef_config_5fupdate_2eproto,
    "config_update.proto",
    &descriptor_table_config_5fupdate_2eproto_once,
    descriptor_table_config_5fupdate_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_config_5fupdate_2eproto::offsets,
    file_level_enum_descriptors_config_5fupdate_2eproto,
    file_level_service_descriptors_config_5fupdate_2eproto,
};
namespace cs {
// ===================================================================

class ConfigUpdate_Request::_Internal {
 public:
};

ConfigUpdate_Request::ConfigUpdate_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ConfigUpdate_Request_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cs.ConfigUpdate.Request)
}
PROTOBUF_NDEBUG_INLINE ConfigUpdate_Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::cs::ConfigUpdate_Request& from_msg)
      : update_file_{visibility, arena, from.update_file_},
        _cached_size_{0} {}

ConfigUpdate_Request::ConfigUpdate_Request(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ConfigUpdate_Request& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ConfigUpdate_Request_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ConfigUpdate_Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:cs.ConfigUpdate.Request)
}
PROTOBUF_NDEBUG_INLINE ConfigUpdate_Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : update_file_{visibility, arena},
        _cached_size_{0} {}

inline void ConfigUpdate_Request::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ConfigUpdate_Request::~ConfigUpdate_Request() {
  // @@protoc_insertion_point(destructor:cs.ConfigUpdate.Request)
  SharedDtor(*this);
}
inline void ConfigUpdate_Request::SharedDtor(MessageLite& self) {
  ConfigUpdate_Request& this_ = static_cast<ConfigUpdate_Request&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ConfigUpdate_Request::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ConfigUpdate_Request(arena);
}
constexpr auto ConfigUpdate_Request::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ConfigUpdate_Request, _impl_.update_file_) +
          decltype(ConfigUpdate_Request::_impl_.update_file_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ConfigUpdate_Request), alignof(ConfigUpdate_Request), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ConfigUpdate_Request::PlacementNew_,
                                 sizeof(ConfigUpdate_Request),
                                 alignof(ConfigUpdate_Request));
  }
}
constexpr auto ConfigUpdate_Request::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ConfigUpdate_Request_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ConfigUpdate_Request::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ConfigUpdate_Request>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ConfigUpdate_Request::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ConfigUpdate_Request>(), &ConfigUpdate_Request::ByteSizeLong,
              &ConfigUpdate_Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ConfigUpdate_Request, _impl_._cached_size_),
          false,
      },
      &ConfigUpdate_Request::kDescriptorMethods,
      &descriptor_table_config_5fupdate_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ConfigUpdate_Request_class_data_ =
            ConfigUpdate_Request::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ConfigUpdate_Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ConfigUpdate_Request_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ConfigUpdate_Request_class_data_.tc_table);
  return ConfigUpdate_Request_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 43, 2>
ConfigUpdate_Request::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ConfigUpdate_Request_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cs::ConfigUpdate_Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string update_file = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ConfigUpdate_Request, _impl_.update_file_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string update_file = 1;
    {PROTOBUF_FIELD_OFFSET(ConfigUpdate_Request, _impl_.update_file_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\27\13\0\0\0\0\0\0"
    "cs.ConfigUpdate.Request"
    "update_file"
  }},
};
PROTOBUF_NOINLINE void ConfigUpdate_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:cs.ConfigUpdate.Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.update_file_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ConfigUpdate_Request::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ConfigUpdate_Request& this_ = static_cast<const ConfigUpdate_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ConfigUpdate_Request::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ConfigUpdate_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:cs.ConfigUpdate.Request)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated string update_file = 1;
  for (int i = 0, n = this_._internal_update_file_size(); i < n; ++i) {
    const auto& s = this_._internal_update_file().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "cs.ConfigUpdate.Request.update_file");
    target = stream->WriteString(1, s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cs.ConfigUpdate.Request)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ConfigUpdate_Request::ByteSizeLong(const MessageLite& base) {
  const ConfigUpdate_Request& this_ = static_cast<const ConfigUpdate_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ConfigUpdate_Request::ByteSizeLong() const {
  const ConfigUpdate_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cs.ConfigUpdate.Request)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated string update_file = 1;
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_update_file().size());
      for (int i = 0, n = this_._internal_update_file().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_update_file().Get(i));
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ConfigUpdate_Request::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ConfigUpdate_Request*>(&to_msg);
  auto& from = static_cast<const ConfigUpdate_Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cs.ConfigUpdate.Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_update_file()->MergeFrom(from._internal_update_file());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConfigUpdate_Request::CopyFrom(const ConfigUpdate_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cs.ConfigUpdate.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ConfigUpdate_Request::InternalSwap(ConfigUpdate_Request* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.update_file_.InternalSwap(&other->_impl_.update_file_);
}

::google::protobuf::Metadata ConfigUpdate_Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ConfigUpdate_Response::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ConfigUpdate_Response>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ConfigUpdate_Response, _impl_._has_bits_);
};

ConfigUpdate_Response::ConfigUpdate_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ConfigUpdate_Response_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cs.ConfigUpdate.Response)
}
ConfigUpdate_Response::ConfigUpdate_Response(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ConfigUpdate_Response& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ConfigUpdate_Response_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ConfigUpdate_Response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ConfigUpdate_Response::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.err_ = {};
}
ConfigUpdate_Response::~ConfigUpdate_Response() {
  // @@protoc_insertion_point(destructor:cs.ConfigUpdate.Response)
  SharedDtor(*this);
}
inline void ConfigUpdate_Response::SharedDtor(MessageLite& self) {
  ConfigUpdate_Response& this_ = static_cast<ConfigUpdate_Response&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ConfigUpdate_Response::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ConfigUpdate_Response(arena);
}
constexpr auto ConfigUpdate_Response::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ConfigUpdate_Response),
                                            alignof(ConfigUpdate_Response));
}
constexpr auto ConfigUpdate_Response::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ConfigUpdate_Response_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ConfigUpdate_Response::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ConfigUpdate_Response>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ConfigUpdate_Response::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ConfigUpdate_Response>(), &ConfigUpdate_Response::ByteSizeLong,
              &ConfigUpdate_Response::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ConfigUpdate_Response, _impl_._cached_size_),
          false,
      },
      &ConfigUpdate_Response::kDescriptorMethods,
      &descriptor_table_config_5fupdate_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ConfigUpdate_Response_class_data_ =
            ConfigUpdate_Response::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ConfigUpdate_Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ConfigUpdate_Response_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ConfigUpdate_Response_class_data_.tc_table);
  return ConfigUpdate_Response_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
ConfigUpdate_Response::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ConfigUpdate_Response, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ConfigUpdate_Response_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cs::ConfigUpdate_Response>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 err = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ConfigUpdate_Response, _impl_.err_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(ConfigUpdate_Response, _impl_.err_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 err = 1;
    {PROTOBUF_FIELD_OFFSET(ConfigUpdate_Response, _impl_.err_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void ConfigUpdate_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:cs.ConfigUpdate.Response)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.err_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ConfigUpdate_Response::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ConfigUpdate_Response& this_ = static_cast<const ConfigUpdate_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ConfigUpdate_Response::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ConfigUpdate_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:cs.ConfigUpdate.Response)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 err = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_err() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_err(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cs.ConfigUpdate.Response)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ConfigUpdate_Response::ByteSizeLong(const MessageLite& base) {
  const ConfigUpdate_Response& this_ = static_cast<const ConfigUpdate_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ConfigUpdate_Response::ByteSizeLong() const {
  const ConfigUpdate_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cs.ConfigUpdate.Response)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 err = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_err() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_err());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ConfigUpdate_Response::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ConfigUpdate_Response*>(&to_msg);
  auto& from = static_cast<const ConfigUpdate_Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:cs.ConfigUpdate.Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (from._internal_err() != 0) {
      _this->_impl_.err_ = from._impl_.err_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConfigUpdate_Response::CopyFrom(const ConfigUpdate_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cs.ConfigUpdate.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ConfigUpdate_Response::InternalSwap(ConfigUpdate_Response* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.err_, other->_impl_.err_);
}

::google::protobuf::Metadata ConfigUpdate_Response::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ConfigUpdate::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ConfigUpdate>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ConfigUpdate, _impl_._has_bits_);
};

ConfigUpdate::ConfigUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ConfigUpdate_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:cs.ConfigUpdate)
}
PROTOBUF_NDEBUG_INLINE ConfigUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::cs::ConfigUpdate& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ConfigUpdate::ConfigUpdate(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ConfigUpdate& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ConfigUpdate_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ConfigUpdate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.request_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.request_)
                : nullptr;
  _impl_.response_ = ((cached_has_bits & 0x00000002u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.response_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:cs.ConfigUpdate)
}
PROTOBUF_NDEBUG_INLINE ConfigUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void ConfigUpdate::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, request_),
           0,
           offsetof(Impl_, response_) -
               offsetof(Impl_, request_) +
               sizeof(Impl_::response_));
}
ConfigUpdate::~ConfigUpdate() {
  // @@protoc_insertion_point(destructor:cs.ConfigUpdate)
  SharedDtor(*this);
}
inline void ConfigUpdate::SharedDtor(MessageLite& self) {
  ConfigUpdate& this_ = static_cast<ConfigUpdate&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.request_;
  delete this_._impl_.response_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ConfigUpdate::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ConfigUpdate(arena);
}
constexpr auto ConfigUpdate::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ConfigUpdate),
                                            alignof(ConfigUpdate));
}
constexpr auto ConfigUpdate::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ConfigUpdate_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ConfigUpdate::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ConfigUpdate>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ConfigUpdate::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ConfigUpdate>(), &ConfigUpdate::ByteSizeLong,
              &ConfigUpdate::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ConfigUpdate, _impl_._cached_size_),
          false,
      },
      &ConfigUpdate::kDescriptorMethods,
      &descriptor_table_config_5fupdate_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ConfigUpdate_class_data_ =
            ConfigUpdate::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL ConfigUpdate::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ConfigUpdate_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ConfigUpdate_class_data_.tc_table);
  return ConfigUpdate_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2>
ConfigUpdate::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ConfigUpdate, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ConfigUpdate_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::cs::ConfigUpdate>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .cs.ConfigUpdate.Response response = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(ConfigUpdate, _impl_.response_)}},
    // .cs.ConfigUpdate.Request request = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ConfigUpdate, _impl_.request_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .cs.ConfigUpdate.Request request = 1;
    {PROTOBUF_FIELD_OFFSET(ConfigUpdate, _impl_.request_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .cs.ConfigUpdate.Response response = 2;
    {PROTOBUF_FIELD_OFFSET(ConfigUpdate, _impl_.response_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::cs::ConfigUpdate_Request>()},
      {::_pbi::TcParser::GetTable<::cs::ConfigUpdate_Response>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ConfigUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:cs.ConfigUpdate)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(_impl_.request_ != nullptr);
      _impl_.request_->Clear();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(_impl_.response_ != nullptr);
      _impl_.response_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ConfigUpdate::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ConfigUpdate& this_ = static_cast<const ConfigUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ConfigUpdate::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ConfigUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:cs.ConfigUpdate)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .cs.ConfigUpdate.Request request = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.request_, this_._impl_.request_->GetCachedSize(), target,
        stream);
  }

  // .cs.ConfigUpdate.Response response = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.response_, this_._impl_.response_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cs.ConfigUpdate)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ConfigUpdate::ByteSizeLong(const MessageLite& base) {
  const ConfigUpdate& this_ = static_cast<const ConfigUpdate&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ConfigUpdate::ByteSizeLong() const {
  const ConfigUpdate& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:cs.ConfigUpdate)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // .cs.ConfigUpdate.Request request = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.request_);
    }
    // .cs.ConfigUpdate.Response response = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.response_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ConfigUpdate::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ConfigUpdate*>(&to_msg);
  auto& from = static_cast<const ConfigUpdate&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:cs.ConfigUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(from._impl_.request_ != nullptr);
      if (_this->_impl_.request_ == nullptr) {
        _this->_impl_.request_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.request_);
      } else {
        _this->_impl_.request_->MergeFrom(*from._impl_.request_);
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(from._impl_.response_ != nullptr);
      if (_this->_impl_.response_ == nullptr) {
        _this->_impl_.response_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.response_);
      } else {
        _this->_impl_.response_->MergeFrom(*from._impl_.response_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ConfigUpdate::CopyFrom(const ConfigUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cs.ConfigUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ConfigUpdate::InternalSwap(ConfigUpdate* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ConfigUpdate, _impl_.response_)
      + sizeof(ConfigUpdate::_impl_.response_)
      - PROTOBUF_FIELD_OFFSET(ConfigUpdate, _impl_.request_)>(
          reinterpret_cast<char*>(&_impl_.request_),
          reinterpret_cast<char*>(&other->_impl_.request_));
}

::google::protobuf::Metadata ConfigUpdate::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace cs
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_config_5fupdate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
