// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: config_update.proto
// Protobuf C++ Version: 6.30.0

#ifndef config_5fupdate_2eproto_2epb_2eh
#define config_5fupdate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "base.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_config_5fupdate_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_config_5fupdate_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_config_5fupdate_2eproto;
}  // extern "C"
namespace cs {
class ConfigUpdate;
struct ConfigUpdateDefaultTypeInternal;
extern ConfigUpdateDefaultTypeInternal _ConfigUpdate_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ConfigUpdate_class_data_;
class ConfigUpdate_Request;
struct ConfigUpdate_RequestDefaultTypeInternal;
extern ConfigUpdate_RequestDefaultTypeInternal _ConfigUpdate_Request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ConfigUpdate_Request_class_data_;
class ConfigUpdate_Response;
struct ConfigUpdate_ResponseDefaultTypeInternal;
extern ConfigUpdate_ResponseDefaultTypeInternal _ConfigUpdate_Response_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ConfigUpdate_Response_class_data_;
}  // namespace cs
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace cs {

// ===================================================================


// -------------------------------------------------------------------

class ConfigUpdate_Response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cs.ConfigUpdate.Response) */ {
 public:
  inline ConfigUpdate_Response() : ConfigUpdate_Response(nullptr) {}
  ~ConfigUpdate_Response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ConfigUpdate_Response* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ConfigUpdate_Response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ConfigUpdate_Response(::google::protobuf::internal::ConstantInitialized);

  inline ConfigUpdate_Response(const ConfigUpdate_Response& from) : ConfigUpdate_Response(nullptr, from) {}
  inline ConfigUpdate_Response(ConfigUpdate_Response&& from) noexcept
      : ConfigUpdate_Response(nullptr, std::move(from)) {}
  inline ConfigUpdate_Response& operator=(const ConfigUpdate_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConfigUpdate_Response& operator=(ConfigUpdate_Response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConfigUpdate_Response& default_instance() {
    return *reinterpret_cast<const ConfigUpdate_Response*>(
        &_ConfigUpdate_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ConfigUpdate_Response& a, ConfigUpdate_Response& b) { a.Swap(&b); }
  inline void Swap(ConfigUpdate_Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConfigUpdate_Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConfigUpdate_Response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ConfigUpdate_Response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ConfigUpdate_Response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ConfigUpdate_Response& from) { ConfigUpdate_Response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ConfigUpdate_Response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cs.ConfigUpdate.Response"; }

 protected:
  explicit ConfigUpdate_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ConfigUpdate_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ConfigUpdate_Response& from);
  ConfigUpdate_Response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ConfigUpdate_Response&& from) noexcept
      : ConfigUpdate_Response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrFieldNumber = 1,
  };
  // int32 err = 1;
  void clear_err() ;
  ::int32_t err() const;
  void set_err(::int32_t value);

  private:
  ::int32_t _internal_err() const;
  void _internal_set_err(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:cs.ConfigUpdate.Response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ConfigUpdate_Response& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t err_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_config_5fupdate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ConfigUpdate_Response_class_data_;
// -------------------------------------------------------------------

class ConfigUpdate_Request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cs.ConfigUpdate.Request) */ {
 public:
  inline ConfigUpdate_Request() : ConfigUpdate_Request(nullptr) {}
  ~ConfigUpdate_Request() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ConfigUpdate_Request* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ConfigUpdate_Request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ConfigUpdate_Request(::google::protobuf::internal::ConstantInitialized);

  inline ConfigUpdate_Request(const ConfigUpdate_Request& from) : ConfigUpdate_Request(nullptr, from) {}
  inline ConfigUpdate_Request(ConfigUpdate_Request&& from) noexcept
      : ConfigUpdate_Request(nullptr, std::move(from)) {}
  inline ConfigUpdate_Request& operator=(const ConfigUpdate_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConfigUpdate_Request& operator=(ConfigUpdate_Request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConfigUpdate_Request& default_instance() {
    return *reinterpret_cast<const ConfigUpdate_Request*>(
        &_ConfigUpdate_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ConfigUpdate_Request& a, ConfigUpdate_Request& b) { a.Swap(&b); }
  inline void Swap(ConfigUpdate_Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConfigUpdate_Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConfigUpdate_Request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ConfigUpdate_Request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ConfigUpdate_Request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ConfigUpdate_Request& from) { ConfigUpdate_Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ConfigUpdate_Request* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cs.ConfigUpdate.Request"; }

 protected:
  explicit ConfigUpdate_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ConfigUpdate_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ConfigUpdate_Request& from);
  ConfigUpdate_Request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ConfigUpdate_Request&& from) noexcept
      : ConfigUpdate_Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUpdateFileFieldNumber = 1,
  };
  // repeated string update_file = 1;
  int update_file_size() const;
  private:
  int _internal_update_file_size() const;

  public:
  void clear_update_file() ;
  const std::string& update_file(int index) const;
  std::string* PROTOBUF_NONNULL mutable_update_file(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_update_file(int index, Arg_&& value, Args_... args);
  std::string* PROTOBUF_NONNULL add_update_file();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_update_file(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& update_file() const;
  ::google::protobuf::RepeatedPtrField<std::string>* PROTOBUF_NONNULL mutable_update_file();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_update_file() const;
  ::google::protobuf::RepeatedPtrField<std::string>* PROTOBUF_NONNULL _internal_mutable_update_file();

  public:
  // @@protoc_insertion_point(class_scope:cs.ConfigUpdate.Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 43,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ConfigUpdate_Request& from_msg);
    ::google::protobuf::RepeatedPtrField<std::string> update_file_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_config_5fupdate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ConfigUpdate_Request_class_data_;
// -------------------------------------------------------------------

class ConfigUpdate final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:cs.ConfigUpdate) */ {
 public:
  inline ConfigUpdate() : ConfigUpdate(nullptr) {}
  ~ConfigUpdate() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ConfigUpdate* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ConfigUpdate));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ConfigUpdate(::google::protobuf::internal::ConstantInitialized);

  inline ConfigUpdate(const ConfigUpdate& from) : ConfigUpdate(nullptr, from) {}
  inline ConfigUpdate(ConfigUpdate&& from) noexcept
      : ConfigUpdate(nullptr, std::move(from)) {}
  inline ConfigUpdate& operator=(const ConfigUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConfigUpdate& operator=(ConfigUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConfigUpdate& default_instance() {
    return *reinterpret_cast<const ConfigUpdate*>(
        &_ConfigUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ConfigUpdate& a, ConfigUpdate& b) { a.Swap(&b); }
  inline void Swap(ConfigUpdate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConfigUpdate* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConfigUpdate* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ConfigUpdate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ConfigUpdate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ConfigUpdate& from) { ConfigUpdate::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ConfigUpdate* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "cs.ConfigUpdate"; }

 protected:
  explicit ConfigUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ConfigUpdate(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ConfigUpdate& from);
  ConfigUpdate(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ConfigUpdate&& from) noexcept
      : ConfigUpdate(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Request = ConfigUpdate_Request;
  using Response = ConfigUpdate_Response;

  // accessors -------------------------------------------------------
  enum : int {
    kRequestFieldNumber = 1,
    kResponseFieldNumber = 2,
  };
  // .cs.ConfigUpdate.Request request = 1;
  bool has_request() const;
  void clear_request() ;
  const ::cs::ConfigUpdate_Request& request() const;
  [[nodiscard]] ::cs::ConfigUpdate_Request* PROTOBUF_NULLABLE release_request();
  ::cs::ConfigUpdate_Request* PROTOBUF_NONNULL mutable_request();
  void set_allocated_request(::cs::ConfigUpdate_Request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_request(::cs::ConfigUpdate_Request* PROTOBUF_NULLABLE value);
  ::cs::ConfigUpdate_Request* PROTOBUF_NULLABLE unsafe_arena_release_request();

  private:
  const ::cs::ConfigUpdate_Request& _internal_request() const;
  ::cs::ConfigUpdate_Request* PROTOBUF_NONNULL _internal_mutable_request();

  public:
  // .cs.ConfigUpdate.Response response = 2;
  bool has_response() const;
  void clear_response() ;
  const ::cs::ConfigUpdate_Response& response() const;
  [[nodiscard]] ::cs::ConfigUpdate_Response* PROTOBUF_NULLABLE release_response();
  ::cs::ConfigUpdate_Response* PROTOBUF_NONNULL mutable_response();
  void set_allocated_response(::cs::ConfigUpdate_Response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_response(::cs::ConfigUpdate_Response* PROTOBUF_NULLABLE value);
  ::cs::ConfigUpdate_Response* PROTOBUF_NULLABLE unsafe_arena_release_response();

  private:
  const ::cs::ConfigUpdate_Response& _internal_response() const;
  ::cs::ConfigUpdate_Response* PROTOBUF_NONNULL _internal_mutable_response();

  public:
  // @@protoc_insertion_point(class_scope:cs.ConfigUpdate)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ConfigUpdate& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::cs::ConfigUpdate_Request* PROTOBUF_NULLABLE request_;
    ::cs::ConfigUpdate_Response* PROTOBUF_NULLABLE response_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_config_5fupdate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ConfigUpdate_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ConfigUpdate_Request

// repeated string update_file = 1;
inline int ConfigUpdate_Request::_internal_update_file_size() const {
  return _internal_update_file().size();
}
inline int ConfigUpdate_Request::update_file_size() const {
  return _internal_update_file_size();
}
inline void ConfigUpdate_Request::clear_update_file() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.update_file_.Clear();
}
inline std::string* PROTOBUF_NONNULL ConfigUpdate_Request::add_update_file()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_update_file()->Add();
  // @@protoc_insertion_point(field_add_mutable:cs.ConfigUpdate.Request.update_file)
  return _s;
}
inline const std::string& ConfigUpdate_Request::update_file(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cs.ConfigUpdate.Request.update_file)
  return _internal_update_file().Get(index);
}
inline std::string* PROTOBUF_NONNULL ConfigUpdate_Request::mutable_update_file(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:cs.ConfigUpdate.Request.update_file)
  return _internal_mutable_update_file()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ConfigUpdate_Request::set_update_file(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_update_file()->Mutable(index), std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:cs.ConfigUpdate.Request.update_file)
}
template <typename Arg_, typename... Args_>
inline void ConfigUpdate_Request::add_update_file(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_update_file(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:cs.ConfigUpdate.Request.update_file)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>& ConfigUpdate_Request::update_file() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:cs.ConfigUpdate.Request.update_file)
  return _internal_update_file();
}
inline ::google::protobuf::RepeatedPtrField<std::string>* PROTOBUF_NONNULL
ConfigUpdate_Request::mutable_update_file() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:cs.ConfigUpdate.Request.update_file)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_update_file();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ConfigUpdate_Request::_internal_update_file() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.update_file_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>* PROTOBUF_NONNULL
ConfigUpdate_Request::_internal_mutable_update_file() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.update_file_;
}

// -------------------------------------------------------------------

// ConfigUpdate_Response

// int32 err = 1;
inline void ConfigUpdate_Response::clear_err() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.err_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t ConfigUpdate_Response::err() const {
  // @@protoc_insertion_point(field_get:cs.ConfigUpdate.Response.err)
  return _internal_err();
}
inline void ConfigUpdate_Response::set_err(::int32_t value) {
  _internal_set_err(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:cs.ConfigUpdate.Response.err)
}
inline ::int32_t ConfigUpdate_Response::_internal_err() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.err_;
}
inline void ConfigUpdate_Response::_internal_set_err(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.err_ = value;
}

// -------------------------------------------------------------------

// ConfigUpdate

// .cs.ConfigUpdate.Request request = 1;
inline bool ConfigUpdate::has_request() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.request_ != nullptr);
  return value;
}
inline void ConfigUpdate::clear_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_ != nullptr) _impl_.request_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::cs::ConfigUpdate_Request& ConfigUpdate::_internal_request() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::cs::ConfigUpdate_Request* p = _impl_.request_;
  return p != nullptr ? *p : reinterpret_cast<const ::cs::ConfigUpdate_Request&>(::cs::_ConfigUpdate_Request_default_instance_);
}
inline const ::cs::ConfigUpdate_Request& ConfigUpdate::request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cs.ConfigUpdate.request)
  return _internal_request();
}
inline void ConfigUpdate::unsafe_arena_set_allocated_request(
    ::cs::ConfigUpdate_Request* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.request_);
  }
  _impl_.request_ = reinterpret_cast<::cs::ConfigUpdate_Request*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cs.ConfigUpdate.request)
}
inline ::cs::ConfigUpdate_Request* PROTOBUF_NULLABLE ConfigUpdate::release_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::cs::ConfigUpdate_Request* released = _impl_.request_;
  _impl_.request_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::cs::ConfigUpdate_Request* PROTOBUF_NULLABLE ConfigUpdate::unsafe_arena_release_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cs.ConfigUpdate.request)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::cs::ConfigUpdate_Request* temp = _impl_.request_;
  _impl_.request_ = nullptr;
  return temp;
}
inline ::cs::ConfigUpdate_Request* PROTOBUF_NONNULL ConfigUpdate::_internal_mutable_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::cs::ConfigUpdate_Request>(GetArena());
    _impl_.request_ = reinterpret_cast<::cs::ConfigUpdate_Request*>(p);
  }
  return _impl_.request_;
}
inline ::cs::ConfigUpdate_Request* PROTOBUF_NONNULL ConfigUpdate::mutable_request()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::cs::ConfigUpdate_Request* _msg = _internal_mutable_request();
  // @@protoc_insertion_point(field_mutable:cs.ConfigUpdate.request)
  return _msg;
}
inline void ConfigUpdate::set_allocated_request(::cs::ConfigUpdate_Request* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.request_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.request_ = reinterpret_cast<::cs::ConfigUpdate_Request*>(value);
  // @@protoc_insertion_point(field_set_allocated:cs.ConfigUpdate.request)
}

// .cs.ConfigUpdate.Response response = 2;
inline bool ConfigUpdate::has_response() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.response_ != nullptr);
  return value;
}
inline void ConfigUpdate::clear_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.response_ != nullptr) _impl_.response_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::cs::ConfigUpdate_Response& ConfigUpdate::_internal_response() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::cs::ConfigUpdate_Response* p = _impl_.response_;
  return p != nullptr ? *p : reinterpret_cast<const ::cs::ConfigUpdate_Response&>(::cs::_ConfigUpdate_Response_default_instance_);
}
inline const ::cs::ConfigUpdate_Response& ConfigUpdate::response() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:cs.ConfigUpdate.response)
  return _internal_response();
}
inline void ConfigUpdate::unsafe_arena_set_allocated_response(
    ::cs::ConfigUpdate_Response* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.response_);
  }
  _impl_.response_ = reinterpret_cast<::cs::ConfigUpdate_Response*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:cs.ConfigUpdate.response)
}
inline ::cs::ConfigUpdate_Response* PROTOBUF_NULLABLE ConfigUpdate::release_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::cs::ConfigUpdate_Response* released = _impl_.response_;
  _impl_.response_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::cs::ConfigUpdate_Response* PROTOBUF_NULLABLE ConfigUpdate::unsafe_arena_release_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:cs.ConfigUpdate.response)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::cs::ConfigUpdate_Response* temp = _impl_.response_;
  _impl_.response_ = nullptr;
  return temp;
}
inline ::cs::ConfigUpdate_Response* PROTOBUF_NONNULL ConfigUpdate::_internal_mutable_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.response_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::cs::ConfigUpdate_Response>(GetArena());
    _impl_.response_ = reinterpret_cast<::cs::ConfigUpdate_Response*>(p);
  }
  return _impl_.response_;
}
inline ::cs::ConfigUpdate_Response* PROTOBUF_NONNULL ConfigUpdate::mutable_response()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::cs::ConfigUpdate_Response* _msg = _internal_mutable_response();
  // @@protoc_insertion_point(field_mutable:cs.ConfigUpdate.response)
  return _msg;
}
inline void ConfigUpdate::set_allocated_response(::cs::ConfigUpdate_Response* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.response_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.response_ = reinterpret_cast<::cs::ConfigUpdate_Response*>(value);
  // @@protoc_insertion_point(field_set_allocated:cs.ConfigUpdate.response)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace cs


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // config_5fupdate_2eproto_2epb_2eh
