// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core_user.proto
// Protobuf C++ Version: 6.30.0

#include "core_user.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace core {
template <typename>
PROTOBUF_CONSTEXPR UsrSvrMappingData_MappingEntry_DoNotUse::UsrSvrMappingData_MappingEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : UsrSvrMappingData_MappingEntry_DoNotUse::MapEntry(UsrSvrMappingData_MappingEntry_DoNotUse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : UsrSvrMappingData_MappingEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct UsrSvrMappingData_MappingEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UsrSvrMappingData_MappingEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UsrSvrMappingData_MappingEntry_DoNotUseDefaultTypeInternal() {}
  union {
    UsrSvrMappingData_MappingEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UsrSvrMappingData_MappingEntry_DoNotUseDefaultTypeInternal _UsrSvrMappingData_MappingEntry_DoNotUse_default_instance_;

inline constexpr UserDataInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        accountid_{::int64_t{0}},
        expire_time_{::int64_t{0}},
        state_{0},
        online_{false},
        last_heartbeat_time_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR UserDataInfo::UserDataInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(UserDataInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UserDataInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UserDataInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UserDataInfoDefaultTypeInternal() {}
  union {
    UserDataInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UserDataInfoDefaultTypeInternal _UserDataInfo_default_instance_;

inline constexpr UsrSvrMappingData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        mapping_{},
        ver_{::int64_t{0}},
        upt_time_{::int64_t{0}},
        connid_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR UsrSvrMappingData::UsrSvrMappingData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(UsrSvrMappingData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UsrSvrMappingDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UsrSvrMappingDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UsrSvrMappingDataDefaultTypeInternal() {}
  union {
    UsrSvrMappingData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UsrSvrMappingDataDefaultTypeInternal _UsrSvrMappingData_default_instance_;
}  // namespace core
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_core_5fuser_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_core_5fuser_2eproto = nullptr;
const ::uint32_t
    TableStruct_core_5fuser_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::core::UsrSvrMappingData_MappingEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::core::UsrSvrMappingData_MappingEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::core::UsrSvrMappingData_MappingEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::core::UsrSvrMappingData_MappingEntry_DoNotUse, _impl_.value_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::core::UsrSvrMappingData, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::core::UsrSvrMappingData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::core::UsrSvrMappingData, _impl_.ver_),
        PROTOBUF_FIELD_OFFSET(::core::UsrSvrMappingData, _impl_.upt_time_),
        PROTOBUF_FIELD_OFFSET(::core::UsrSvrMappingData, _impl_.connid_),
        PROTOBUF_FIELD_OFFSET(::core::UsrSvrMappingData, _impl_.mapping_),
        0,
        1,
        2,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::core::UserDataInfo, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::core::UserDataInfo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::core::UserDataInfo, _impl_.accountid_),
        PROTOBUF_FIELD_OFFSET(::core::UserDataInfo, _impl_.expire_time_),
        PROTOBUF_FIELD_OFFSET(::core::UserDataInfo, _impl_.state_),
        PROTOBUF_FIELD_OFFSET(::core::UserDataInfo, _impl_.online_),
        PROTOBUF_FIELD_OFFSET(::core::UserDataInfo, _impl_.last_heartbeat_time_),
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::core::UsrSvrMappingData_MappingEntry_DoNotUse)},
        {12, 24, -1, sizeof(::core::UsrSvrMappingData)},
        {28, 41, -1, sizeof(::core::UserDataInfo)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::core::_UsrSvrMappingData_MappingEntry_DoNotUse_default_instance_._instance,
    &::core::_UsrSvrMappingData_default_instance_._instance,
    &::core::_UserDataInfo_default_instance_._instance,
};
const char descriptor_table_protodef_core_5fuser_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017core_user.proto\022\004core\"\251\001\n\021UsrSvrMappin"
    "gData\022\013\n\003ver\030\001 \001(\003\022\020\n\010upt_time\030\002 \001(\003\022\016\n\006"
    "connid\030\003 \001(\003\0225\n\007mapping\030\004 \003(\0132$.core.Usr"
    "SvrMappingData.MappingEntry\032.\n\014MappingEn"
    "try\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\r:\0028\001\"r\n\014U"
    "serDataInfo\022\021\n\taccountid\030\001 \001(\003\022\023\n\013expire"
    "_time\030\002 \001(\003\022\r\n\005state\030\003 \001(\005\022\016\n\006online\030\004 \001"
    "(\010\022\033\n\023last_heartbeat_time\030\005 \001(\003b\006proto3"
};
static ::absl::once_flag descriptor_table_core_5fuser_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_core_5fuser_2eproto = {
    false,
    false,
    319,
    descriptor_table_protodef_core_5fuser_2eproto,
    "core_user.proto",
    &descriptor_table_core_5fuser_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_core_5fuser_2eproto::offsets,
    file_level_enum_descriptors_core_5fuser_2eproto,
    file_level_service_descriptors_core_5fuser_2eproto,
};
namespace core {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
UsrSvrMappingData_MappingEntry_DoNotUse::UsrSvrMappingData_MappingEntry_DoNotUse()
    : SuperType(UsrSvrMappingData_MappingEntry_DoNotUse_class_data_.base()) {}
UsrSvrMappingData_MappingEntry_DoNotUse::UsrSvrMappingData_MappingEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, UsrSvrMappingData_MappingEntry_DoNotUse_class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
UsrSvrMappingData_MappingEntry_DoNotUse::UsrSvrMappingData_MappingEntry_DoNotUse() : SuperType() {}
UsrSvrMappingData_MappingEntry_DoNotUse::UsrSvrMappingData_MappingEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
inline void* PROTOBUF_NONNULL UsrSvrMappingData_MappingEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UsrSvrMappingData_MappingEntry_DoNotUse(arena);
}
constexpr auto UsrSvrMappingData_MappingEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UsrSvrMappingData_MappingEntry_DoNotUse),
                                            alignof(UsrSvrMappingData_MappingEntry_DoNotUse));
}
constexpr auto UsrSvrMappingData_MappingEntry_DoNotUse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UsrSvrMappingData_MappingEntry_DoNotUse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &UsrSvrMappingData_MappingEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UsrSvrMappingData_MappingEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UsrSvrMappingData_MappingEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&UsrSvrMappingData_MappingEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UsrSvrMappingData_MappingEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
      &UsrSvrMappingData_MappingEntry_DoNotUse::kDescriptorMethods,
      &descriptor_table_core_5fuser_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        UsrSvrMappingData_MappingEntry_DoNotUse_class_data_ =
            UsrSvrMappingData_MappingEntry_DoNotUse::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL UsrSvrMappingData_MappingEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UsrSvrMappingData_MappingEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UsrSvrMappingData_MappingEntry_DoNotUse_class_data_.tc_table);
  return UsrSvrMappingData_MappingEntry_DoNotUse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
UsrSvrMappingData_MappingEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UsrSvrMappingData_MappingEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    UsrSvrMappingData_MappingEntry_DoNotUse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::core::UsrSvrMappingData_MappingEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 value = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UsrSvrMappingData_MappingEntry_DoNotUse, _impl_.value_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(UsrSvrMappingData_MappingEntry_DoNotUse, _impl_.value_)}},
    // int32 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UsrSvrMappingData_MappingEntry_DoNotUse, _impl_.key_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(UsrSvrMappingData_MappingEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 key = 1;
    {PROTOBUF_FIELD_OFFSET(UsrSvrMappingData_MappingEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // uint32 value = 2;
    {PROTOBUF_FIELD_OFFSET(UsrSvrMappingData_MappingEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
// ===================================================================

class UsrSvrMappingData::_Internal {
 public:
  using HasBits =
      decltype(std::declval<UsrSvrMappingData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_._has_bits_);
};

UsrSvrMappingData::UsrSvrMappingData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UsrSvrMappingData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:core.UsrSvrMappingData)
}
PROTOBUF_NDEBUG_INLINE UsrSvrMappingData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::core::UsrSvrMappingData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        mapping_{visibility, arena, from.mapping_} {}

UsrSvrMappingData::UsrSvrMappingData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UsrSvrMappingData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UsrSvrMappingData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UsrSvrMappingData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ver_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, ver_),
           offsetof(Impl_, connid_) -
               offsetof(Impl_, ver_) +
               sizeof(Impl_::connid_));

  // @@protoc_insertion_point(copy_constructor:core.UsrSvrMappingData)
}
PROTOBUF_NDEBUG_INLINE UsrSvrMappingData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        mapping_{visibility, arena} {}

inline void UsrSvrMappingData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ver_),
           0,
           offsetof(Impl_, connid_) -
               offsetof(Impl_, ver_) +
               sizeof(Impl_::connid_));
}
UsrSvrMappingData::~UsrSvrMappingData() {
  // @@protoc_insertion_point(destructor:core.UsrSvrMappingData)
  SharedDtor(*this);
}
inline void UsrSvrMappingData::SharedDtor(MessageLite& self) {
  UsrSvrMappingData& this_ = static_cast<UsrSvrMappingData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL UsrSvrMappingData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UsrSvrMappingData(arena);
}
constexpr auto UsrSvrMappingData::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.mapping_) +
          decltype(UsrSvrMappingData::_impl_.mapping_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.mapping_) +
          decltype(UsrSvrMappingData::_impl_.mapping_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(UsrSvrMappingData), alignof(UsrSvrMappingData), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&UsrSvrMappingData::PlacementNew_,
                                 sizeof(UsrSvrMappingData),
                                 alignof(UsrSvrMappingData));
  }
}
constexpr auto UsrSvrMappingData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UsrSvrMappingData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &UsrSvrMappingData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UsrSvrMappingData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UsrSvrMappingData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<UsrSvrMappingData>(), &UsrSvrMappingData::ByteSizeLong,
              &UsrSvrMappingData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_._cached_size_),
          false,
      },
      &UsrSvrMappingData::kDescriptorMethods,
      &descriptor_table_core_5fuser_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        UsrSvrMappingData_class_data_ =
            UsrSvrMappingData::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL UsrSvrMappingData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UsrSvrMappingData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UsrSvrMappingData_class_data_.tc_table);
  return UsrSvrMappingData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2>
UsrSvrMappingData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    UsrSvrMappingData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::core::UsrSvrMappingData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 ver = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UsrSvrMappingData, _impl_.ver_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.ver_)}},
    // int64 upt_time = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UsrSvrMappingData, _impl_.upt_time_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.upt_time_)}},
    // int64 connid = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UsrSvrMappingData, _impl_.connid_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.connid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 ver = 1;
    {PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.ver_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 upt_time = 2;
    {PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.upt_time_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 connid = 3;
    {PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.connid_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // map<int32, uint32> mapping = 4;
    {PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.mapping_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }},
  {{
      {::_pbi::TcParser::GetMapAuxInfo(0, 0, 0,
                                       5, 13,
                                       0)},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void UsrSvrMappingData::Clear() {
// @@protoc_insertion_point(message_clear_start:core.UsrSvrMappingData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.mapping_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    ::memset(&_impl_.ver_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.connid_) -
        reinterpret_cast<char*>(&_impl_.ver_)) + sizeof(_impl_.connid_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UsrSvrMappingData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UsrSvrMappingData& this_ = static_cast<const UsrSvrMappingData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UsrSvrMappingData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UsrSvrMappingData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:core.UsrSvrMappingData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 ver = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_ver() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_ver(), target);
    }
  }

  // int64 upt_time = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_upt_time() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_upt_time(), target);
    }
  }

  // int64 connid = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_connid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
              stream, this_._internal_connid(), target);
    }
  }

  // map<int32, uint32> mapping = 4;
  if (!this_._internal_mapping().empty()) {
    using MapType = ::google::protobuf::Map<::int32_t, ::uint32_t>;
    using WireHelper = _pbi::MapEntryFuncs<::int32_t, ::uint32_t,
                                   _pbi::WireFormatLite::TYPE_INT32,
                                   _pbi::WireFormatLite::TYPE_UINT32>;
    const auto& field = this_._internal_mapping();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            4, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            4, entry.first, entry.second, target, stream);
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:core.UsrSvrMappingData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UsrSvrMappingData::ByteSizeLong(const MessageLite& base) {
  const UsrSvrMappingData& this_ = static_cast<const UsrSvrMappingData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UsrSvrMappingData::ByteSizeLong() const {
  const UsrSvrMappingData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:core.UsrSvrMappingData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // map<int32, uint32> mapping = 4;
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_mapping_size());
      for (const auto& entry : this_._internal_mapping()) {
        total_size += _pbi::MapEntryFuncs<::int32_t, ::uint32_t,
                                       _pbi::WireFormatLite::TYPE_INT32,
                                       _pbi::WireFormatLite::TYPE_UINT32>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // int64 ver = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_ver() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_ver());
      }
    }
    // int64 upt_time = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_upt_time() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_upt_time());
      }
    }
    // int64 connid = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_connid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_connid());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UsrSvrMappingData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UsrSvrMappingData*>(&to_msg);
  auto& from = static_cast<const UsrSvrMappingData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:core.UsrSvrMappingData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.mapping_.MergeFrom(from._impl_.mapping_);
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_ver() != 0) {
        _this->_impl_.ver_ = from._impl_.ver_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_upt_time() != 0) {
        _this->_impl_.upt_time_ = from._impl_.upt_time_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_connid() != 0) {
        _this->_impl_.connid_ = from._impl_.connid_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UsrSvrMappingData::CopyFrom(const UsrSvrMappingData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:core.UsrSvrMappingData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UsrSvrMappingData::InternalSwap(UsrSvrMappingData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.mapping_.InternalSwap(&other->_impl_.mapping_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.connid_)
      + sizeof(UsrSvrMappingData::_impl_.connid_)
      - PROTOBUF_FIELD_OFFSET(UsrSvrMappingData, _impl_.ver_)>(
          reinterpret_cast<char*>(&_impl_.ver_),
          reinterpret_cast<char*>(&other->_impl_.ver_));
}

::google::protobuf::Metadata UsrSvrMappingData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UserDataInfo::_Internal {
 public:
  using HasBits =
      decltype(std::declval<UserDataInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_._has_bits_);
};

UserDataInfo::UserDataInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UserDataInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:core.UserDataInfo)
}
UserDataInfo::UserDataInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UserDataInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UserDataInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE UserDataInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void UserDataInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, accountid_),
           0,
           offsetof(Impl_, last_heartbeat_time_) -
               offsetof(Impl_, accountid_) +
               sizeof(Impl_::last_heartbeat_time_));
}
UserDataInfo::~UserDataInfo() {
  // @@protoc_insertion_point(destructor:core.UserDataInfo)
  SharedDtor(*this);
}
inline void UserDataInfo::SharedDtor(MessageLite& self) {
  UserDataInfo& this_ = static_cast<UserDataInfo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL UserDataInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UserDataInfo(arena);
}
constexpr auto UserDataInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(UserDataInfo),
                                            alignof(UserDataInfo));
}
constexpr auto UserDataInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UserDataInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &UserDataInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UserDataInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UserDataInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<UserDataInfo>(), &UserDataInfo::ByteSizeLong,
              &UserDataInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_._cached_size_),
          false,
      },
      &UserDataInfo::kDescriptorMethods,
      &descriptor_table_core_5fuser_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        UserDataInfo_class_data_ =
            UserDataInfo::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL UserDataInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UserDataInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UserDataInfo_class_data_.tc_table);
  return UserDataInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
UserDataInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    UserDataInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::core::UserDataInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 accountid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UserDataInfo, _impl_.accountid_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.accountid_)}},
    // int64 expire_time = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UserDataInfo, _impl_.expire_time_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.expire_time_)}},
    // int32 state = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(UserDataInfo, _impl_.state_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.state_)}},
    // bool online = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UserDataInfo, _impl_.online_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.online_)}},
    // int64 last_heartbeat_time = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UserDataInfo, _impl_.last_heartbeat_time_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.last_heartbeat_time_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 accountid = 1;
    {PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.accountid_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int64 expire_time = 2;
    {PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.expire_time_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int32 state = 3;
    {PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.state_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bool online = 4;
    {PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.online_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // int64 last_heartbeat_time = 5;
    {PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.last_heartbeat_time_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void UserDataInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:core.UserDataInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    ::memset(&_impl_.accountid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.last_heartbeat_time_) -
        reinterpret_cast<char*>(&_impl_.accountid_)) + sizeof(_impl_.last_heartbeat_time_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UserDataInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UserDataInfo& this_ = static_cast<const UserDataInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UserDataInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UserDataInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:core.UserDataInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 accountid = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_accountid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_accountid(), target);
    }
  }

  // int64 expire_time = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_expire_time() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_expire_time(), target);
    }
  }

  // int32 state = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_state() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_state(), target);
    }
  }

  // bool online = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (this_._internal_online() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_online(), target);
    }
  }

  // int64 last_heartbeat_time = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (this_._internal_last_heartbeat_time() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<5>(
              stream, this_._internal_last_heartbeat_time(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:core.UserDataInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UserDataInfo::ByteSizeLong(const MessageLite& base) {
  const UserDataInfo& this_ = static_cast<const UserDataInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UserDataInfo::ByteSizeLong() const {
  const UserDataInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:core.UserDataInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // int64 accountid = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_accountid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_accountid());
      }
    }
    // int64 expire_time = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_expire_time() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_expire_time());
      }
    }
    // int32 state = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_state() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_state());
      }
    }
    // bool online = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (this_._internal_online() != 0) {
        total_size += 2;
      }
    }
    // int64 last_heartbeat_time = 5;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (this_._internal_last_heartbeat_time() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_last_heartbeat_time());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UserDataInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UserDataInfo*>(&to_msg);
  auto& from = static_cast<const UserDataInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:core.UserDataInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_accountid() != 0) {
        _this->_impl_.accountid_ = from._impl_.accountid_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_expire_time() != 0) {
        _this->_impl_.expire_time_ = from._impl_.expire_time_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_state() != 0) {
        _this->_impl_.state_ = from._impl_.state_;
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (from._internal_online() != 0) {
        _this->_impl_.online_ = from._impl_.online_;
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (from._internal_last_heartbeat_time() != 0) {
        _this->_impl_.last_heartbeat_time_ = from._impl_.last_heartbeat_time_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UserDataInfo::CopyFrom(const UserDataInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:core.UserDataInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UserDataInfo::InternalSwap(UserDataInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.last_heartbeat_time_)
      + sizeof(UserDataInfo::_impl_.last_heartbeat_time_)
      - PROTOBUF_FIELD_OFFSET(UserDataInfo, _impl_.accountid_)>(
          reinterpret_cast<char*>(&_impl_.accountid_),
          reinterpret_cast<char*>(&other->_impl_.accountid_));
}

::google::protobuf::Metadata UserDataInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace core
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_core_5fuser_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
