// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core_user.proto
// Protobuf C++ Version: 6.30.0

#ifndef core_5fuser_2eproto_2epb_2eh
#define core_5fuser_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_type_handler.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_core_5fuser_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_core_5fuser_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_core_5fuser_2eproto;
}  // extern "C"
namespace core {
class UserDataInfo;
struct UserDataInfoDefaultTypeInternal;
extern UserDataInfoDefaultTypeInternal _UserDataInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UserDataInfo_class_data_;
class UsrSvrMappingData;
struct UsrSvrMappingDataDefaultTypeInternal;
extern UsrSvrMappingDataDefaultTypeInternal _UsrSvrMappingData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UsrSvrMappingData_class_data_;
class UsrSvrMappingData_MappingEntry_DoNotUse;
struct UsrSvrMappingData_MappingEntry_DoNotUseDefaultTypeInternal;
extern UsrSvrMappingData_MappingEntry_DoNotUseDefaultTypeInternal _UsrSvrMappingData_MappingEntry_DoNotUse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UsrSvrMappingData_MappingEntry_DoNotUse_class_data_;
}  // namespace core
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace core {

// ===================================================================


// -------------------------------------------------------------------

class UsrSvrMappingData_MappingEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<::int32_t, ::uint32_t,
                             ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                             ::google::protobuf::internal::WireFormatLite::TYPE_UINT32> {
 public:
  using SuperType =
      ::google::protobuf::internal::MapEntry<::int32_t, ::uint32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>;
  UsrSvrMappingData_MappingEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UsrSvrMappingData_MappingEntry_DoNotUse(::google::protobuf::internal::ConstantInitialized);
  explicit UsrSvrMappingData_MappingEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr const void* PROTOBUF_NONNULL internal_default_instance() {
    return &_UsrSvrMappingData_MappingEntry_DoNotUse_default_instance_;
  }


  static constexpr auto InternalGenerateClassData_();

 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_core_5fuser_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();
};
extern const ::google::protobuf::internal::ClassDataFull UsrSvrMappingData_MappingEntry_DoNotUse_class_data_;
// -------------------------------------------------------------------

class UserDataInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:core.UserDataInfo) */ {
 public:
  inline UserDataInfo() : UserDataInfo(nullptr) {}
  ~UserDataInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UserDataInfo* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UserDataInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UserDataInfo(::google::protobuf::internal::ConstantInitialized);

  inline UserDataInfo(const UserDataInfo& from) : UserDataInfo(nullptr, from) {}
  inline UserDataInfo(UserDataInfo&& from) noexcept
      : UserDataInfo(nullptr, std::move(from)) {}
  inline UserDataInfo& operator=(const UserDataInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserDataInfo& operator=(UserDataInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserDataInfo& default_instance() {
    return *reinterpret_cast<const UserDataInfo*>(
        &_UserDataInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(UserDataInfo& a, UserDataInfo& b) { a.Swap(&b); }
  inline void Swap(UserDataInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserDataInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserDataInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UserDataInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UserDataInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UserDataInfo& from) { UserDataInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UserDataInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "core.UserDataInfo"; }

 protected:
  explicit UserDataInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  UserDataInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UserDataInfo& from);
  UserDataInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, UserDataInfo&& from) noexcept
      : UserDataInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAccountidFieldNumber = 1,
    kExpireTimeFieldNumber = 2,
    kStateFieldNumber = 3,
    kOnlineFieldNumber = 4,
    kLastHeartbeatTimeFieldNumber = 5,
  };
  // int64 accountid = 1;
  void clear_accountid() ;
  ::int64_t accountid() const;
  void set_accountid(::int64_t value);

  private:
  ::int64_t _internal_accountid() const;
  void _internal_set_accountid(::int64_t value);

  public:
  // int64 expire_time = 2;
  void clear_expire_time() ;
  ::int64_t expire_time() const;
  void set_expire_time(::int64_t value);

  private:
  ::int64_t _internal_expire_time() const;
  void _internal_set_expire_time(::int64_t value);

  public:
  // int32 state = 3;
  void clear_state() ;
  ::int32_t state() const;
  void set_state(::int32_t value);

  private:
  ::int32_t _internal_state() const;
  void _internal_set_state(::int32_t value);

  public:
  // bool online = 4;
  void clear_online() ;
  bool online() const;
  void set_online(bool value);

  private:
  bool _internal_online() const;
  void _internal_set_online(bool value);

  public:
  // int64 last_heartbeat_time = 5;
  void clear_last_heartbeat_time() ;
  ::int64_t last_heartbeat_time() const;
  void set_last_heartbeat_time(::int64_t value);

  private:
  ::int64_t _internal_last_heartbeat_time() const;
  void _internal_set_last_heartbeat_time(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:core.UserDataInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const UserDataInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t accountid_;
    ::int64_t expire_time_;
    ::int32_t state_;
    bool online_;
    ::int64_t last_heartbeat_time_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_5fuser_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UserDataInfo_class_data_;
// -------------------------------------------------------------------

class UsrSvrMappingData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:core.UsrSvrMappingData) */ {
 public:
  inline UsrSvrMappingData() : UsrSvrMappingData(nullptr) {}
  ~UsrSvrMappingData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UsrSvrMappingData* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UsrSvrMappingData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UsrSvrMappingData(::google::protobuf::internal::ConstantInitialized);

  inline UsrSvrMappingData(const UsrSvrMappingData& from) : UsrSvrMappingData(nullptr, from) {}
  inline UsrSvrMappingData(UsrSvrMappingData&& from) noexcept
      : UsrSvrMappingData(nullptr, std::move(from)) {}
  inline UsrSvrMappingData& operator=(const UsrSvrMappingData& from) {
    CopyFrom(from);
    return *this;
  }
  inline UsrSvrMappingData& operator=(UsrSvrMappingData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UsrSvrMappingData& default_instance() {
    return *reinterpret_cast<const UsrSvrMappingData*>(
        &_UsrSvrMappingData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(UsrSvrMappingData& a, UsrSvrMappingData& b) { a.Swap(&b); }
  inline void Swap(UsrSvrMappingData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UsrSvrMappingData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UsrSvrMappingData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UsrSvrMappingData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UsrSvrMappingData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UsrSvrMappingData& from) { UsrSvrMappingData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UsrSvrMappingData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "core.UsrSvrMappingData"; }

 protected:
  explicit UsrSvrMappingData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  UsrSvrMappingData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UsrSvrMappingData& from);
  UsrSvrMappingData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, UsrSvrMappingData&& from) noexcept
      : UsrSvrMappingData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMappingFieldNumber = 4,
    kVerFieldNumber = 1,
    kUptTimeFieldNumber = 2,
    kConnidFieldNumber = 3,
  };
  // map<int32, uint32> mapping = 4;
  int mapping_size() const;
  private:
  int _internal_mapping_size() const;

  public:
  void clear_mapping() ;
  const ::google::protobuf::Map<::int32_t, ::uint32_t>& mapping() const;
  ::google::protobuf::Map<::int32_t, ::uint32_t>* PROTOBUF_NONNULL mutable_mapping();

  private:
  const ::google::protobuf::Map<::int32_t, ::uint32_t>& _internal_mapping() const;
  ::google::protobuf::Map<::int32_t, ::uint32_t>* PROTOBUF_NONNULL _internal_mutable_mapping();

  public:
  // int64 ver = 1;
  void clear_ver() ;
  ::int64_t ver() const;
  void set_ver(::int64_t value);

  private:
  ::int64_t _internal_ver() const;
  void _internal_set_ver(::int64_t value);

  public:
  // int64 upt_time = 2;
  void clear_upt_time() ;
  ::int64_t upt_time() const;
  void set_upt_time(::int64_t value);

  private:
  ::int64_t _internal_upt_time() const;
  void _internal_set_upt_time(::int64_t value);

  public:
  // int64 connid = 3;
  void clear_connid() ;
  ::int64_t connid() const;
  void set_connid(::int64_t value);

  private:
  ::int64_t _internal_connid() const;
  void _internal_set_connid(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:core.UsrSvrMappingData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const UsrSvrMappingData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::MapField<UsrSvrMappingData_MappingEntry_DoNotUse, ::int32_t, ::uint32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
                      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>
        mapping_;
    ::int64_t ver_;
    ::int64_t upt_time_;
    ::int64_t connid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_core_5fuser_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UsrSvrMappingData_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// UsrSvrMappingData

// int64 ver = 1;
inline void UsrSvrMappingData::clear_ver() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ver_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t UsrSvrMappingData::ver() const {
  // @@protoc_insertion_point(field_get:core.UsrSvrMappingData.ver)
  return _internal_ver();
}
inline void UsrSvrMappingData::set_ver(::int64_t value) {
  _internal_set_ver(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:core.UsrSvrMappingData.ver)
}
inline ::int64_t UsrSvrMappingData::_internal_ver() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ver_;
}
inline void UsrSvrMappingData::_internal_set_ver(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ver_ = value;
}

// int64 upt_time = 2;
inline void UsrSvrMappingData::clear_upt_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.upt_time_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t UsrSvrMappingData::upt_time() const {
  // @@protoc_insertion_point(field_get:core.UsrSvrMappingData.upt_time)
  return _internal_upt_time();
}
inline void UsrSvrMappingData::set_upt_time(::int64_t value) {
  _internal_set_upt_time(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:core.UsrSvrMappingData.upt_time)
}
inline ::int64_t UsrSvrMappingData::_internal_upt_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.upt_time_;
}
inline void UsrSvrMappingData::_internal_set_upt_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.upt_time_ = value;
}

// int64 connid = 3;
inline void UsrSvrMappingData::clear_connid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.connid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t UsrSvrMappingData::connid() const {
  // @@protoc_insertion_point(field_get:core.UsrSvrMappingData.connid)
  return _internal_connid();
}
inline void UsrSvrMappingData::set_connid(::int64_t value) {
  _internal_set_connid(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:core.UsrSvrMappingData.connid)
}
inline ::int64_t UsrSvrMappingData::_internal_connid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.connid_;
}
inline void UsrSvrMappingData::_internal_set_connid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.connid_ = value;
}

// map<int32, uint32> mapping = 4;
inline int UsrSvrMappingData::_internal_mapping_size() const {
  return _internal_mapping().size();
}
inline int UsrSvrMappingData::mapping_size() const {
  return _internal_mapping_size();
}
inline void UsrSvrMappingData::clear_mapping() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mapping_.Clear();
}
inline const ::google::protobuf::Map<::int32_t, ::uint32_t>& UsrSvrMappingData::_internal_mapping() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.mapping_.GetMap();
}
inline const ::google::protobuf::Map<::int32_t, ::uint32_t>& UsrSvrMappingData::mapping() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:core.UsrSvrMappingData.mapping)
  return _internal_mapping();
}
inline ::google::protobuf::Map<::int32_t, ::uint32_t>* PROTOBUF_NONNULL UsrSvrMappingData::_internal_mutable_mapping() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.mapping_.MutableMap();
}
inline ::google::protobuf::Map<::int32_t, ::uint32_t>* PROTOBUF_NONNULL UsrSvrMappingData::mutable_mapping()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:core.UsrSvrMappingData.mapping)
  return _internal_mutable_mapping();
}

// -------------------------------------------------------------------

// UserDataInfo

// int64 accountid = 1;
inline void UserDataInfo::clear_accountid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accountid_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t UserDataInfo::accountid() const {
  // @@protoc_insertion_point(field_get:core.UserDataInfo.accountid)
  return _internal_accountid();
}
inline void UserDataInfo::set_accountid(::int64_t value) {
  _internal_set_accountid(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:core.UserDataInfo.accountid)
}
inline ::int64_t UserDataInfo::_internal_accountid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.accountid_;
}
inline void UserDataInfo::_internal_set_accountid(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.accountid_ = value;
}

// int64 expire_time = 2;
inline void UserDataInfo::clear_expire_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expire_time_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t UserDataInfo::expire_time() const {
  // @@protoc_insertion_point(field_get:core.UserDataInfo.expire_time)
  return _internal_expire_time();
}
inline void UserDataInfo::set_expire_time(::int64_t value) {
  _internal_set_expire_time(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:core.UserDataInfo.expire_time)
}
inline ::int64_t UserDataInfo::_internal_expire_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.expire_time_;
}
inline void UserDataInfo::_internal_set_expire_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expire_time_ = value;
}

// int32 state = 3;
inline void UserDataInfo::clear_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t UserDataInfo::state() const {
  // @@protoc_insertion_point(field_get:core.UserDataInfo.state)
  return _internal_state();
}
inline void UserDataInfo::set_state(::int32_t value) {
  _internal_set_state(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:core.UserDataInfo.state)
}
inline ::int32_t UserDataInfo::_internal_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.state_;
}
inline void UserDataInfo::_internal_set_state(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.state_ = value;
}

// bool online = 4;
inline void UserDataInfo::clear_online() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.online_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool UserDataInfo::online() const {
  // @@protoc_insertion_point(field_get:core.UserDataInfo.online)
  return _internal_online();
}
inline void UserDataInfo::set_online(bool value) {
  _internal_set_online(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:core.UserDataInfo.online)
}
inline bool UserDataInfo::_internal_online() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.online_;
}
inline void UserDataInfo::_internal_set_online(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.online_ = value;
}

// int64 last_heartbeat_time = 5;
inline void UserDataInfo::clear_last_heartbeat_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.last_heartbeat_time_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int64_t UserDataInfo::last_heartbeat_time() const {
  // @@protoc_insertion_point(field_get:core.UserDataInfo.last_heartbeat_time)
  return _internal_last_heartbeat_time();
}
inline void UserDataInfo::set_last_heartbeat_time(::int64_t value) {
  _internal_set_last_heartbeat_time(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:core.UserDataInfo.last_heartbeat_time)
}
inline ::int64_t UserDataInfo::_internal_last_heartbeat_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.last_heartbeat_time_;
}
inline void UserDataInfo::_internal_set_last_heartbeat_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.last_heartbeat_time_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace core


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // core_5fuser_2eproto_2epb_2eh
