// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gate.proto
// Protobuf C++ Version: 6.30.0

#ifndef gate_2eproto_2epb_2eh
#define gate_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_gate_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_gate_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_gate_2eproto;
}  // extern "C"
class Heart;
struct HeartDefaultTypeInternal;
extern HeartDefaultTypeInternal _Heart_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Heart_class_data_;
class Heart_Request;
struct Heart_RequestDefaultTypeInternal;
extern Heart_RequestDefaultTypeInternal _Heart_Request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Heart_Request_class_data_;
class Heart_Response;
struct Heart_ResponseDefaultTypeInternal;
extern Heart_ResponseDefaultTypeInternal _Heart_Response_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Heart_Response_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Heart_Response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Heart.Response) */ {
 public:
  inline Heart_Response() : Heart_Response(nullptr) {}
  ~Heart_Response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Heart_Response* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Heart_Response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Heart_Response(::google::protobuf::internal::ConstantInitialized);

  inline Heart_Response(const Heart_Response& from) : Heart_Response(nullptr, from) {}
  inline Heart_Response(Heart_Response&& from) noexcept
      : Heart_Response(nullptr, std::move(from)) {}
  inline Heart_Response& operator=(const Heart_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Heart_Response& operator=(Heart_Response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Heart_Response& default_instance() {
    return *reinterpret_cast<const Heart_Response*>(
        &_Heart_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Heart_Response& a, Heart_Response& b) { a.Swap(&b); }
  inline void Swap(Heart_Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Heart_Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Heart_Response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Heart_Response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Heart_Response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Heart_Response& from) { Heart_Response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Heart_Response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Heart.Response"; }

 protected:
  explicit Heart_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Heart_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Heart_Response& from);
  Heart_Response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Heart_Response&& from) noexcept
      : Heart_Response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimestampFieldNumber = 2,
    kErrFieldNumber = 1,
  };
  // int64 timestamp = 2;
  void clear_timestamp() ;
  ::int64_t timestamp() const;
  void set_timestamp(::int64_t value);

  private:
  ::int64_t _internal_timestamp() const;
  void _internal_set_timestamp(::int64_t value);

  public:
  // int32 err = 1;
  void clear_err() ;
  ::int32_t err() const;
  void set_err(::int32_t value);

  private:
  ::int32_t _internal_err() const;
  void _internal_set_err(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Heart.Response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Heart_Response& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t timestamp_;
    ::int32_t err_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Heart_Response_class_data_;
// -------------------------------------------------------------------

class Heart_Request final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Heart.Request) */ {
 public:
  inline Heart_Request() : Heart_Request(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Heart_Request* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Heart_Request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Heart_Request(::google::protobuf::internal::ConstantInitialized);

  inline Heart_Request(const Heart_Request& from) : Heart_Request(nullptr, from) {}
  inline Heart_Request(Heart_Request&& from) noexcept
      : Heart_Request(nullptr, std::move(from)) {}
  inline Heart_Request& operator=(const Heart_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Heart_Request& operator=(Heart_Request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Heart_Request& default_instance() {
    return *reinterpret_cast<const Heart_Request*>(
        &_Heart_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Heart_Request& a, Heart_Request& b) { a.Swap(&b); }
  inline void Swap(Heart_Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Heart_Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Heart_Request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<Heart_Request>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Heart_Request& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Heart_Request& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Heart.Request"; }

 protected:
  explicit Heart_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Heart_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Heart_Request& from);
  Heart_Request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Heart_Request&& from) noexcept
      : Heart_Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Heart.Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Heart_Request& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_gate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Heart_Request_class_data_;
// -------------------------------------------------------------------

class Heart final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Heart) */ {
 public:
  inline Heart() : Heart(nullptr) {}
  ~Heart() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Heart* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Heart));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Heart(::google::protobuf::internal::ConstantInitialized);

  inline Heart(const Heart& from) : Heart(nullptr, from) {}
  inline Heart(Heart&& from) noexcept
      : Heart(nullptr, std::move(from)) {}
  inline Heart& operator=(const Heart& from) {
    CopyFrom(from);
    return *this;
  }
  inline Heart& operator=(Heart&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Heart& default_instance() {
    return *reinterpret_cast<const Heart*>(
        &_Heart_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Heart& a, Heart& b) { a.Swap(&b); }
  inline void Swap(Heart* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Heart* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Heart* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Heart>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Heart& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Heart& from) { Heart::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Heart* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Heart"; }

 protected:
  explicit Heart(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Heart(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Heart& from);
  Heart(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Heart&& from) noexcept
      : Heart(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Request = Heart_Request;
  using Response = Heart_Response;

  // accessors -------------------------------------------------------
  enum : int {
    kRequestFieldNumber = 1,
    kResponseFieldNumber = 2,
  };
  // .Heart.Request request = 1;
  bool has_request() const;
  void clear_request() ;
  const ::Heart_Request& request() const;
  [[nodiscard]] ::Heart_Request* PROTOBUF_NULLABLE release_request();
  ::Heart_Request* PROTOBUF_NONNULL mutable_request();
  void set_allocated_request(::Heart_Request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_request(::Heart_Request* PROTOBUF_NULLABLE value);
  ::Heart_Request* PROTOBUF_NULLABLE unsafe_arena_release_request();

  private:
  const ::Heart_Request& _internal_request() const;
  ::Heart_Request* PROTOBUF_NONNULL _internal_mutable_request();

  public:
  // .Heart.Response response = 2;
  bool has_response() const;
  void clear_response() ;
  const ::Heart_Response& response() const;
  [[nodiscard]] ::Heart_Response* PROTOBUF_NULLABLE release_response();
  ::Heart_Response* PROTOBUF_NONNULL mutable_response();
  void set_allocated_response(::Heart_Response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_response(::Heart_Response* PROTOBUF_NULLABLE value);
  ::Heart_Response* PROTOBUF_NULLABLE unsafe_arena_release_response();

  private:
  const ::Heart_Response& _internal_response() const;
  ::Heart_Response* PROTOBUF_NONNULL _internal_mutable_response();

  public:
  // @@protoc_insertion_point(class_scope:Heart)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Heart& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Heart_Request* PROTOBUF_NULLABLE request_;
    ::Heart_Response* PROTOBUF_NULLABLE response_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gate_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Heart_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Heart_Request

// -------------------------------------------------------------------

// Heart_Response

// int32 err = 1;
inline void Heart_Response::clear_err() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.err_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t Heart_Response::err() const {
  // @@protoc_insertion_point(field_get:Heart.Response.err)
  return _internal_err();
}
inline void Heart_Response::set_err(::int32_t value) {
  _internal_set_err(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:Heart.Response.err)
}
inline ::int32_t Heart_Response::_internal_err() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.err_;
}
inline void Heart_Response::_internal_set_err(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.err_ = value;
}

// int64 timestamp = 2;
inline void Heart_Response::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int64_t Heart_Response::timestamp() const {
  // @@protoc_insertion_point(field_get:Heart.Response.timestamp)
  return _internal_timestamp();
}
inline void Heart_Response::set_timestamp(::int64_t value) {
  _internal_set_timestamp(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:Heart.Response.timestamp)
}
inline ::int64_t Heart_Response::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void Heart_Response::_internal_set_timestamp(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// -------------------------------------------------------------------

// Heart

// .Heart.Request request = 1;
inline bool Heart::has_request() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.request_ != nullptr);
  return value;
}
inline void Heart::clear_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_ != nullptr) _impl_.request_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Heart_Request& Heart::_internal_request() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Heart_Request* p = _impl_.request_;
  return p != nullptr ? *p : reinterpret_cast<const ::Heart_Request&>(::_Heart_Request_default_instance_);
}
inline const ::Heart_Request& Heart::request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Heart.request)
  return _internal_request();
}
inline void Heart::unsafe_arena_set_allocated_request(
    ::Heart_Request* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.request_);
  }
  _impl_.request_ = reinterpret_cast<::Heart_Request*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Heart.request)
}
inline ::Heart_Request* PROTOBUF_NULLABLE Heart::release_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Heart_Request* released = _impl_.request_;
  _impl_.request_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Heart_Request* PROTOBUF_NULLABLE Heart::unsafe_arena_release_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Heart.request)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Heart_Request* temp = _impl_.request_;
  _impl_.request_ = nullptr;
  return temp;
}
inline ::Heart_Request* PROTOBUF_NONNULL Heart::_internal_mutable_request() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.request_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Heart_Request>(GetArena());
    _impl_.request_ = reinterpret_cast<::Heart_Request*>(p);
  }
  return _impl_.request_;
}
inline ::Heart_Request* PROTOBUF_NONNULL Heart::mutable_request()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Heart_Request* _msg = _internal_mutable_request();
  // @@protoc_insertion_point(field_mutable:Heart.request)
  return _msg;
}
inline void Heart::set_allocated_request(::Heart_Request* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.request_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.request_ = reinterpret_cast<::Heart_Request*>(value);
  // @@protoc_insertion_point(field_set_allocated:Heart.request)
}

// .Heart.Response response = 2;
inline bool Heart::has_response() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.response_ != nullptr);
  return value;
}
inline void Heart::clear_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.response_ != nullptr) _impl_.response_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::Heart_Response& Heart::_internal_response() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Heart_Response* p = _impl_.response_;
  return p != nullptr ? *p : reinterpret_cast<const ::Heart_Response&>(::_Heart_Response_default_instance_);
}
inline const ::Heart_Response& Heart::response() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Heart.response)
  return _internal_response();
}
inline void Heart::unsafe_arena_set_allocated_response(
    ::Heart_Response* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.response_);
  }
  _impl_.response_ = reinterpret_cast<::Heart_Response*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Heart.response)
}
inline ::Heart_Response* PROTOBUF_NULLABLE Heart::release_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Heart_Response* released = _impl_.response_;
  _impl_.response_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Heart_Response* PROTOBUF_NULLABLE Heart::unsafe_arena_release_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Heart.response)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::Heart_Response* temp = _impl_.response_;
  _impl_.response_ = nullptr;
  return temp;
}
inline ::Heart_Response* PROTOBUF_NONNULL Heart::_internal_mutable_response() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.response_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Heart_Response>(GetArena());
    _impl_.response_ = reinterpret_cast<::Heart_Response*>(p);
  }
  return _impl_.response_;
}
inline ::Heart_Response* PROTOBUF_NONNULL Heart::mutable_response()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::Heart_Response* _msg = _internal_mutable_response();
  // @@protoc_insertion_point(field_mutable:Heart.response)
  return _msg;
}
inline void Heart::set_allocated_response(::Heart_Response* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.response_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.response_ = reinterpret_cast<::Heart_Response*>(value);
  // @@protoc_insertion_point(field_set_allocated:Heart.response)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // gate_2eproto_2epb_2eh
